name: DevSecOps Workflow

on:
  push:

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Build Job Echo Statement
        run: echo "Build Job is Running"

      - name: Step 2 in Build Job Sleep
        run: sleep 10

  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Step 1 in Test Job Echo Statement
        run: echo "Test Job is Running"
      
      - name: Step 2 in Test Job Sleep
        run: sleep 10
